create table features_added(
"year" int,
"month" int,
DayofMonth int,
FlightDate TIMESTAMP WITH TIME ZONE,
Marketing_AirLine_Network char(2),
OriginCityName char(25),
DestCityName char(25),
DepTime int,
DepDelay int,
DepDelayMinutes int, 
TaxiOut int,
Taxiin int,
ArrTime int, 
ArrDelay int,
ArrDelayMinutes int,
CRSElapsedTime int,
ActualElapsedTime int,
AirTime int,
Distance int,
DistanceGroup int,
CarrierDelay int, 
WeatherDelay int,
NASDelay int, 
SecurityDelay int, 
LateAircraftDelay int,
Dayofweek int,
Holidays bool,
CRSDeptTimeMinute int,
CRSDeptTimeHour int,
WheelsoffMinute int,
WheelsoffHour int,
CRSArrTimeMinute int,
CRSArrTimeHour int,
WheelsOnMinute int,
WheelsOnHour int,
CRSDepTimeHourDis char(20),
WheelsoffHourDis char(20),
CRSArrTimeHourDis char(20),
WheelsonHourDis char(20),
CRSElapsedTimeGroup int,
PRIMARY KEY ("year", "month", DayofMonth, Marketing_AirLine_Network, OriginCityName, DestCityName),
FOREIGN KEY (OriginCityName) REFERENCES City(city_name),
FOREIGN KEY (DestCityName) REFERENCES City(city_name)
);

create table Flight_Delay(
"year" int,
"month" int,
DayofMonth int,
FlightDate date,
Marketing_AirLine_Network char(2),
OriginCityName char(25),
DestCityName char(25),
CRSDepTime int,
DepTime int,
DepDelay int,
DepDelayMinutes int, 
TaxiOut int,
WheelsOff int, 
WheelsOn int, 
Taxiin int,
CRSArrTime int, 
ArrTime int, 
ArrDelay int,
ArrDelayMinutes int,
CRSElapsedTime int,
ActualElapsedTime int,
AirTime int,
Distance int,
DistanceGroup int,
CarrierDelay int, 
WeatherDelay int,
NASDelay int, 
SecurityDelay int, 
LateAircraftDelay int,
PRIMARY KEY (year, month, DayofMonth, Marketing_AirLine_Network, OriginCityName, DestCityName, CRSDepTime),
FOREIGN KEY (year, month, DayofMonth, Marketing_AirLine_Network, OriginCityName, DestCityName)
        REFERENCES features_added (year, month, DayofMonth, Marketing_AirLine_Network, OriginCityName, DestCityName),
FOREIGN KEY (OriginCityName) REFERENCES City(city_name),
FOREIGN KEY (DestCityName) REFERENCES City(city_name)
);